name: apay
description: AirbaPaySdk

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^1.1.6 #почему-то версия 2.0.~ ломает иконку спортмастера
  flutter_bloc: ^8.1.3
  intl: ^0.18.1
  equatable: ^2.0.5
  formz: ^0.6.0
  dio: ^5.2.1+1
  json_annotation: ^4.8.1
  simple_logger: ^1.9.0+2
  webview_flutter: ^4.2.2
  video_player: ^2.7.0
  local_auth: ^2.1.6

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

dev_dependencies:
  json_serializable: ^6.7.0
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    # https://flutter.dev/assets-and-images/#resolution-aware
    # https://flutter.dev/assets-and-images/#from-packages
    - assets/images/sportmasters.svg
    - assets/images/airba_pay.svg
    - assets/images/MasterCard.svg
    - assets/images/Visa.svg
    - assets/images/AmericanExpress.svg
    - assets/images/Hint.svg
    - assets/images/ic_close.svg
    - assets/images/line_gray.svg
    - assets/images/cancel.svg
    - assets/images/Alarm.svg
    - assets/images/mir.svg
    - assets/images/union-pay.svg
    - assets/images/maestro-card.svg
    - assets/images/warning_red_oval.svg
    - assets/images/pay_success.svg
    - assets/images/pay_failed.svg
    - assets/images/something_wrong.svg
    - assets/images/ic_add.svg
    - assets/images/g_pay.svg
    - assets/images/ic_radio_button_off.svg
    - assets/images/ic_radio_button_on.svg

  # https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Monserrat
      fonts:
        - asset: assets/font/regular.ttf #400
        - asset: assets/font/medium.ttf #500
        - asset: assets/font/semi_bold.ttf #600
        - asset: assets/font/bold.ttf #700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #



  # This section identifies your Flutter project as a module meant for
  # embedding in a native host app.  These identifiers should _not_ ordinarily
  # be changed after generation - they are used to ensure that the tooling can
  # maintain consistency when adding or modifying assets and plugins.
  # They also do not have any bearing on your native host application's
  # identifiers, which may be completely independent or the same as these.
  module:
    androidX: true
    androidPackage: kz.airbapay.apay
    iosBundleIdentifier: kz.airbapay.apay
